# M - Automated Essay Scoring
_School of Information Technology_<br>
_Monash University Malaysia_<br>
(c) Copyright 2020, Ian Tan & Jun Qing Lim

Steps

- Read dataset (ASAP)
- Extract features (into file) using EASE
- Conduct machine learning (Sci-kit Learn libraries)
    - Naive Bayes
    - SVR
    - BLRR (later)
- Evaluate (QWK)

## Import Libraries

In [202]:
import time
start = time.time()

In [203]:
import numpy as np
import pandas as pd
from collections import defaultdict

from nltk import pos_tag
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer

from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import model_selection, naive_bayes, svm #SVR is in SVM
from sklearn.metrics import accuracy_score, confusion_matrix

### Import the EASE functions, which is located in the ease folder.

In [204]:
import sys
sys.path.insert(1, 'ease')
import create
import grade 
import model_creator 
import predictor_extractor 
import predictor_set 
import util_functions
import essay_set
import feature_extractor

from essay_set import EssaySet
from feature_extractor import FeatureExtractor

## Read Dataset

AES (Hewlett Foundation dataset from Kaggle) in the folder `asap-aes`.  For this, we use the `training_set_rel3` for training and testing.  Note that the `test_set` and the `valid_set` cannot be used as they don't contain the scores and are meant for the competition to score the entries.

In [205]:
data_set = pd.read_csv("asap-aes/training_set_rel3.tsv", sep='\t', encoding="latin-1")

In [206]:
data_set['essay'] = [entry.lower() for entry in data_set['essay']] # lower case for all words in essay

There are 8 different essay sets.  As an overview:
- Sets 1 & 2 are of persuasive/narrative in the form of letters
- Sets 3, 4, 5 & 6 are source dependent response to a given essay
- Sets 7 & 8 are of persuasive/narrative in the form of story writing essays

These format makes it good for transfer learning.

In [207]:
data_set_1 = data_set[data_set['essay_set'] == 1]
data_set_2 = data_set[data_set['essay_set'] == 2]
#data_set_3 = data_set[data_set['essay_set'] == 3]
#data_set_4 = data_set[data_set['essay_set'] == 4]
#data_set_5 = data_set[data_set['essay_set'] == 5]
#data_set_6 = data_set[data_set['essay_set'] == 6]
data_set_7 = data_set[data_set['essay_set'] == 7]
data_set_8 = data_set[data_set['essay_set'] == 8]

As each set will retain the original index, we want each of them to have their own indexing so that it is easier to match the essay and the scores.

In [208]:
data_set_1 = data_set_1.reset_index() # resets index
data_set_2 = data_set_2.reset_index()
#data_set_3 = data_set_3.reset_index()
#data_set_4 = data_set_4.reset_index()
#data_set_5 = data_set_5.reset_index()
#data_set_6 = data_set_6.reset_index()
data_set_7 = data_set_7.reset_index()
data_set_8 = data_set_8.reset_index()

We use just the `essay` content and the respective `scores`.

In [209]:
# If you want for the whole dataset.
# Commented out as we will work on individual datasets
#essays = data_set['essay']
#scores = data_set['domain1_score']

In [210]:
essays_1 = data_set_1['essay']
scores_1 = data_set_1['domain1_score']
essays_2 = data_set_2['essay']
scores_2 = data_set_2['domain1_score']
#essays_3 = data_set_3['essay']
#scores_3 = data_set_3['domain1_score']
#essays_4 = data_set_4['essay']
#scores_4 = data_set_4['domain1_score']
#essays_5 = data_set_5['essay']
#scores_5 = data_set_5['domain1_score']
#essays_6 = data_set_6['essay']
#scores_6 = data_set_6['domain1_score']
essays_7 = data_set_7['essay']
scores_7 = data_set_7['domain1_score']
essays_8 = data_set_8['essay']
scores_8 = data_set_8['domain1_score']

Rename the `domain1_score` column to `score`.

In [211]:
scores_1.columns = "score"
scores_2.columns = "score"
#scores_3.columns = "score"
#scores_4.columns = "score"
#scores_5.columns = "score"
#scores_6.columns = "score"
scores_7.columns = "score"
scores_8.columns = "score"

THE ABOVE NEEDS TO BE PUT INTO A LOOP BUT I LEFT IT AS IS BECAUSE YOU CAN PICK AND CHOOSE EASILY INSTEAD.

### Create the essay sets

Again, these can be looped but I kept them separated for ease of readability and commenting out those that we don't need.  Each set takes a long time to process, and hence please be patient with this part.

In [212]:
e_set_1 = EssaySet()
e_set_2 = EssaySet()
#e_set_3 = EssaySet()
#e_set_4 = EssaySet()
#e_set_5 = EssaySet()
#e_set_6 = EssaySet()
e_set_7 = EssaySet()
e_set_8 = EssaySet()

In [213]:
for i in range(len(essays_1)):
    e_set_1.add_essay(essays_1[i], scores_1[i])

In [214]:
for i in range(len(essays_2)):
    e_set_2.add_essay(essays_2[i], scores_2[i])

Left out for sets 3 - 6 for now.

In [215]:
for i in range(len(essays_7)):
    e_set_7.add_essay(essays_7[i], scores_7[i])

In [216]:
for i in range(len(essays_8)):
    e_set_8.add_essay(essays_8[i], scores_8[i])

## Extract Features

Currently only doing for Set 1

In [217]:
f_extractor = FeatureExtractor()

Change the next two variable assignment to change the evaluation of the essay sets.

In [218]:
e_set = e_set_7
score = scores_7

In [219]:
length = f_extractor.gen_length_feats(e_set)
length_df_1 = pd.DataFrame(
    length, 
    columns = [
        'chars', 
        'words', 
        'commas', 
        'apostrophes', 
        'punctuations', 
        'avg_word_length',
        # new stuff
        'sentences',
        'questions',
        'avg_word_sentence',
        'POS', 
        'POS/total_words'
    ]
)

_*Exclude the prompts for the time being*_

In [220]:
# Merge this with the score based on the index
# We use the shallow features first
features = length_df_1
dataset = features.merge(score, left_index=True, right_index=True)
dataset.columns = ['chars', 'words', 'commas', 'apostrophes', 'punctuations',
                   'avg_word_length', 'sentences', 'questions', 'avg_word_sentence',
                   'POS', 'POS/total_words', 'score']
X_1 = dataset.iloc[:,0:10].values.astype(float)
y_1 = dataset.iloc[:,11].values.astype(float)

Reshape the data and label

In [221]:
X_1.shape

(1569, 10)

In [222]:
y_1 = np.array(y_1).reshape(-1,1)
y_1.shape

(1569, 1)

In [223]:
### Split the train and test set
from sklearn.model_selection import train_test_split
X_1_train, X_1_test, y_1_train, y_1_test = train_test_split(X_1, y_1, test_size=0.2, random_state=0)
# Have a look at the first few lines
print(y_1_test[:5, :])

[[13.]
 [24.]
 [13.]
 [17.]
 [ 8.]]


## Model Training

In [224]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

### Naive Bayes Training

No scaling used for Naive Bayes

In [225]:
X_1_trainNB = X_1_train
y_1_trainNB = y_1_train
X_1_testNB = X_1_test
y_1_testNB = y_1_test

In [226]:
model_nb_1 = naive_bayes.MultinomialNB()
model_nb_1.fit(X_1_trainNB, y_1_trainNB.ravel())

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

At this stage, the Naive Bayes model is called `model_nb_1`

### SVM Training

Use standard scaler for the data

In [227]:
from sklearn.preprocessing import StandardScaler
sc_Xsvm = StandardScaler()
sc_ysvm = StandardScaler()
X_1_trainSVM = sc_Xsvm.fit_transform(X_1_train)
y_1_trainSVM = sc_ysvm.fit_transform(y_1_train)
X_1_testSVM = sc_Xsvm.transform(X_1_test)
y_1_testSVM = sc_ysvm.transform(y_1_test)

In [228]:
from sklearn.svm import SVR
# most important SVR parameter is Kernel type. It can be #linear,polynomial or gaussian SVR. We have a non-linear condition #so we can select polynomial or gaussian but here we select RBF(a #gaussian type) kernel.
# kernel{‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘precomputed’}, default=’rbf’
# maybe use poly and increase the degree
model_svm_1 = SVR(kernel='rbf', gamma='auto', verbose=True)
#regressor = SVR(kernel='poly', degree=5, gamma='auto', verbose=True)
model_svm_1.fit(X_1_trainSVM,y_1_trainSVM.ravel())

[LibSVM]

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=True)

At this stage, the Support Vector Machine (SVM) model is called `model_svm_1`

### BLRR

In [229]:
from sklearn.preprocessing import StandardScaler
sc_Xblrr = StandardScaler()
sc_yblrr = StandardScaler()
X_1_trainBLRR = sc_Xblrr.fit_transform(X_1_train)
y_1_trainBLRR = sc_yblrr.fit_transform(y_1_train)
X_1_testBLRR = sc_Xblrr.transform(X_1_test)
y_1_testBLRR = sc_yblrr.transform(y_1_test)

In [230]:
from sklearn import linear_model
model_blrr_1 = linear_model.BayesianRidge()
model_blrr_1.fit(X_1_trainBLRR, y_1_trainBLRR.ravel())

BayesianRidge(alpha_1=1e-06, alpha_2=1e-06, compute_score=False, copy_X=True,
       fit_intercept=True, lambda_1=1e-06, lambda_2=1e-06, n_iter=300,
       normalize=False, tol=0.001, verbose=False)

At this stage, the Bayesian Linear Ridge Regression (BLRR) model is called `model_blrr_1`

## Prediction

We will be using the respective validation set and will have to also pre-process the data.

### Naive Bayes

In [231]:
y_1_predNB = model_nb_1.predict(X_1_testNB)
#y_1_predNB = sc_ynb.inverse_transform(y_1_predNB).round()

cm = confusion_matrix(y_1_test, y_1_predNB)
print(cm)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  3  1  0  0  0  0  1  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  3  4  3  1  0  0  2  0  0  3  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  2  2  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  1  0  1  0  0  0  1  5  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  1  1  2  1  0  0  1  0  2  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  3  1  3  2  0  0  0  0  0  1  0  0  0  0  0  0  0  1]
 [ 1  0  0  0  1  2  5  3  0  0  0  0  1  6  2  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  2  2  0  0  3  0  0  1  7  2  0  1  0  0  0  0  0]
 [ 0  0  0  1  0  1  2  1  1  0  2  2  0 12  2  1  0  0  1  0  1  1]
 [ 0  0  0  0  0  2  5  1  1  0  1  0  0  8  2  1  1  1  5  3  0  2]
 [ 0  0  0  1  0  1  2  0  0  0  1

### SVM

In [232]:
y_1_predSVM = model_svm_1.predict(X_1_testSVM)
y_1_predSVM = sc_ysvm.inverse_transform(y_1_predSVM).round()

cm = confusion_matrix(y_1_test, y_1_predSVM)
print(cm)

[[ 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  1  2  0  0  0  0  1  1  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  5  2  3  0  1  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  2  1  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  1  0  2  1  1  3  0  1  0  1  0  0  0  0  0]
 [ 0  0  0  1  1  1  0  2  2  1  0  0  1  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  2  0  3  3  0  1  1  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  1  1  2  2  3  3  4  2  2  0  1  0  0  1  0  0]
 [ 0  0  0  0  0  1  0  1  4  4  4  1  2  1  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  1  0  3  8  4  1  3  4  2  1  0  0  0  0]
 [ 0  0  0  0  0  0  1  1  5  3  4  4  3  3  6  3  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  7  6 10  5  6  3  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  1  1  3  5  6  5  1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  1  8  1  0  1  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  1  0  1  3  5  1  2  0  2  0

In [233]:
# y_1_predSVM

### BLRR

In [234]:
y_1_predBLRR = model_blrr_1.predict(X_1_testBLRR)
y_1_predBLRR = sc_yblrr.inverse_transform(y_1_predBLRR).round()

cm = confusion_matrix(y_1_test, y_1_predBLRR)
print(cm)

[[ 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  2  2  0  1  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  3  8  5  0  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  2  3  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  1  4  3  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  3  2  2  1  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  2  5  2  0  0  0  0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  1  4  6  4  4  1  1  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  4  7  1  3  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  1  5  9  2  5  3  1  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  1  4  8  4  4  5  1  1  2  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  8  3 11  6  5  1  3  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  1  3  5  6  3  4  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  2  7  1  0  1  1  0  0  2  0  0]
 [ 0  0  0

## Evaluation using QWK

QWK scores for NB, SVR and BLRR

In [235]:
from sklearn.metrics import classification_report
from sklearn.metrics import cohen_kappa_score

### Naive Bayes

In [236]:
rpt = classification_report(y_1_test, y_1_predNB)
print(rpt)

              precision    recall  f1-score   support

         2.0       0.00      0.00      0.00         0
         4.0       0.00      0.00      0.00         1
         5.0       0.00      0.00      0.00         0
         6.0       0.00      0.00      0.00         2
         7.0       0.00      0.00      0.00         7
         8.0       0.18      0.22      0.20        18
         9.0       0.07      0.33      0.11         6
        10.0       0.00      0.00      0.00        11
        11.0       0.20      0.10      0.13        10
        12.0       0.00      0.00      0.00        11
        13.0       0.00      0.00      0.00        22
        14.0       0.00      0.00      0.00        18
        15.0       0.00      0.00      0.00        28
        16.0       0.11      0.24      0.16        33
        17.0       0.19      0.16      0.17        38
        18.0       0.00      0.00      0.00        24
        19.0       0.00      0.00      0.00        14
        20.0       0.00    

D:\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [237]:
print(cohen_kappa_score(y_1_test, y_1_predNB, weights="quadratic"))

0.6474149199029923


### SVM

In [238]:
rpt = classification_report(y_1_test, y_1_predSVM)
print(rpt)

              precision    recall  f1-score   support

         4.0       0.00      0.00      0.00         1
         6.0       0.00      0.00      0.00         2
         7.0       0.00      0.00      0.00         7
         8.0       0.00      0.00      0.00        18
         9.0       0.00      0.00      0.00         6
        10.0       0.07      0.09      0.08        11
        11.0       0.00      0.00      0.00        10
        12.0       0.20      0.27      0.23        11
        13.0       0.12      0.14      0.13        22
        14.0       0.17      0.22      0.19        18
        15.0       0.12      0.14      0.13        28
        16.0       0.17      0.12      0.14        33
        17.0       0.23      0.26      0.25        38
        18.0       0.19      0.25      0.22        24
        19.0       0.00      0.00      0.00        14
        20.0       0.00      0.00      0.00        16
        21.0       0.11      0.06      0.08        17
        22.0       0.00    

D:\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [239]:
print(cohen_kappa_score(y_1_test, y_1_predSVM, weights="quadratic"))

0.7200545006594828


### BLRR

In [240]:
rpt = classification_report(y_1_test, y_1_predBLRR)
print(rpt)

              precision    recall  f1-score   support

         4.0       0.00      0.00      0.00         1
         6.0       0.00      0.00      0.00         2
         7.0       0.00      0.00      0.00         7
         8.0       0.00      0.00      0.00        18
         9.0       0.00      0.00      0.00         6
        10.0       0.00      0.00      0.00        11
        11.0       0.08      0.10      0.09        10
        12.0       0.08      0.18      0.11        11
        13.0       0.16      0.27      0.20        22
        14.0       0.14      0.39      0.21        18
        15.0       0.07      0.07      0.07        28
        16.0       0.09      0.12      0.11        33
        17.0       0.18      0.16      0.17        38
        18.0       0.14      0.12      0.13        24
        19.0       0.05      0.07      0.06        14
        20.0       0.00      0.00      0.00        16
        21.0       0.12      0.06      0.08        17
        22.0       0.17    

In [241]:
print(cohen_kappa_score(y_1_test, y_1_predBLRR, weights="quadratic"))

0.684625181033411


In [242]:
end = time.time()
print("Total time to execute the notebook is " + str(end - start))

Total time to execute the notebook is 304.00941824913025


# END

#### Collate the essay prompts
This consist of one essay from each set

In [193]:
essay_prompts = []

# Takes a bit of time also :)
for i in range(1,9):
    file = "prompts/set" + str(i) + ".txt"
    f = open(file, "r", encoding="latin-1") # there are some 0x9x characters, hence need to specify encoding
    essay_prompts.append(f.read())
    
def get_essay_prompt(essay_set):
    return essay_prompts[essay_set-1]

In [194]:
# Unsure how this works
e_set.update_prompt(get_essay_prompt(2))

# Need more explanation on how this works - look into EASE

prompts = f_extractor.gen_prompt_feats(e_set)
prompts_df = pd.DataFrame(prompts, columns = ['prompt_words', 'prompt_words/total_words', 'synonym_words', 'synonym_words/total_words'])

NameError: name 'e_set' is not defined

In [ ]:
e_set

In [ ]:
# Another process that takes sometime to process
unstemmed = util_functions.get_vocab_essays_count(e_set._text, e_set._score)
stemmed = util_functions.get_vocab_essays_count(e_set._clean_stem_text, e_set._score)

bow = list(map(lambda a,b:[a,b], unstemmed, stemmed))
bow_df = pd.DataFrame(bow, columns = ['unstemmed', 'stemmed'])

In [ ]:
features = pd.concat([length_df, prompts_df, bow_df], axis=1, sort=False)

In [ ]:
features.head()

In [ ]:
# Export features to a file for next stage (optional)
dataset = features.merge(scores, left_index=True, right_index=True)

In [ ]:
dataset.head()

In [ ]:
dataset.columns = ['chars', 'words', 'commas', 'apostrophes', 'punctuations',
       'avg_word_length', 'POS', 'POS/total_words', 'prompt_words',
       'prompt_words/total_words', 'synonym_words',
       'synonym_words/total_words', 'unstemmed', 'stemmed', 'score']

In [ ]:
dataset.head()

In [ ]:
dataset.to_csv('maes_features.csv')

Can just use the features and score for the X and y but just to keep to certain convention if reading back from the CSV file above.


In [ ]:
X = dataset.iloc[:,0:13].values.astype(float)
y = dataset.iloc[:,14].values.astype(float)

In [ ]:
y

In [ ]:
X.shape

In [ ]:
y = np.array(y).reshape(-1,1)
y.shape

#### Conduct Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y)

In [ ]:
len(X)

In [ ]:
len(y)

#### Split the train and test sets

In [ ]:
# To split the train / test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
# Have a look at the first few lines
print(y_test[:5, :])

### Training

#### Support Vector Regression

In [ ]:
from sklearn.svm import SVR
# most important SVR parameter is Kernel type. It can be #linear,polynomial or gaussian SVR. We have a non-linear condition #so we can select polynomial or gaussian but here we select RBF(a #gaussian type) kernel.
# kernel{‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘precomputed’}, default=’rbf’
# maybe use poly and increase the degree
regressor = SVR(kernel='rbf', gamma='auto', verbose=True)
#regressor = SVR(kernel='poly', degree=5, gamma='auto', verbose=True)
regressor.fit(X_train,y_train.ravel())

#### Test / Predict the fit

In [ ]:
# Not used yet as I don't have a sample X
y_pred = regressor.predict(X_test)
y_pred = sc_y.inverse_transform(y_pred).round()

In [ ]:
df = pd.DataFrame(
    {
        'Real Values':sc_y.inverse_transform(y_test.reshape(-1)),
        'Predicted Values':y_pred
    }
)
df.head()

#### Accuracy Score

In [ ]:
# y_pred

In [ ]:
# y_test = sc_y.inverse_transform(y_test).round()
# y_test.ravel()

In [ ]:
# Need to wrap my head around this (where's the predictor)

print("accuracy score:", regressor.score(X_test, y_test))

In [ ]:
print("accuracy score:", accuracy_score(df['Real Values'], df['Predicted Values']))

In [ ]:
from sklearn.metrics import cohen_kappa_score

In [ ]:
print(cohen_kappa_score(sc_y.inverse_transform(y_test).round(), y_pred, weights="quadratic"))

### Naive Bayes

In [ ]:
X_train

In [ ]:
X_train_test = sc_X.inverse_transform(X_train)
X_train_test = X_train_test.astype(int)
X_train_test

In [ ]:
y_train_test = sc_y.inverse_transform(y_train.reshape(-1))
y_train_test = y_train_test.astype(int)
y_train_test

In [ ]:
nbclassifier = naive_bayes.MultinomialNB()
nbclassifier.fit(X_train_test, y_train_test)

In [ ]:
X_test_test = sc_X.inverse_transform(X_test)
X_test_test = X_test_test.astype(int)
X_test_test

In [ ]:
y_test_test = sc_y.inverse_transform(y_test.reshape(-1))
y_test_test = y_test_test.astype(int)
y_test_test

In [ ]:
y_predNB = nbclassifier.predict(X_test_test)

cm = confusion_matrix(y_test_test, y_predNB)
print(cm)

In [ ]:
from sklearn.metrics import classification_report

rpt = classification_report(y_test_test, y_predNB)
print(rpt)

### QWK Scores (Manual Code)

In [ ]:
N = len(cm) # Just to get the same size as the confusion matrix from above
w = np.zeros((N,N)) # create a matrix of N by N
d = (N-1)**2 # the weighted portion
for i in range(len(w)):
    for j in range(len(w)):
        w[i][j] = float(((i-j)**2)/d) 
w # The weighted matrix

In [ ]:
N

In [ ]:
np.unique(y_test_test)

In [ ]:
np.unique(y_predNB)

In [ ]:
act_hist=np.zeros([N])
for item in y_test_test: 
    act_hist[item-1] += 1

In [ ]:
pred_hist=np.zeros([N])
for item in y_predNB: 
    pred_hist[item-1]+=1

In [ ]:
E = np.outer(act_hist, pred_hist)
E

In [ ]:
E = E/E.sum()
E.sum()

In [ ]:
cm = cm/cm.sum()
cm.sum()

In [ ]:
num=0
den=0
for i in range(len(w)):
    for j in range(len(w)):
        num+=w[i][j]*cm[i][j]
        den+=w[i][j]*E[i][j]
            
weighted_kappa = (1 - (num/den))
weighted_kappa

QWK scores output are from -1 to 1, where -1 means that it is totally wrong while 1 is a perfect match (classification).  The aim is to get as close as possible to 1, with a score of 0.6 being generally accepted as a good score.

### QWK for Naive Bayes

The above code is a manual computation of the QWK, which we later found that it is already available as an option with the [Cohen Kappa Score](https://journals.sagepub.com/doi/10.1177/001316446002000104) in sklearn, when we set the weights to 'quadratic'.  Since it has already been manually coded above, we use the sklearn.metrics.cohen_kappa_score to validate our manual coded scoring. 

In [ ]:
y_test_test

In [ ]:
y_predNB

In [ ]:
print(cohen_kappa_score(y_test_test, y_predNB))
print(cohen_kappa_score(y_test_test, y_predNB, weights="quadratic"))

On the output of the QWK agreements, the score is just "moderate agreement".  Work now is to achieve substantial agreement.

https://www.statisticshowto.com/cohens-kappa-statistic/

In short, SVM works a little better than Naive Bayes for AES.

# End